CREATE TABLE note_table (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  note_name TEXT NOT NULL,
  content TEXT NOT NULL,
  folder INTEGER REFERENCES folder_table(id) ON DELETE CASCADE NOT NULL
);

-- Line 5 is telling us that if we delete a folder, then it will delete all
-- the notes within that folder